"""create surveys table

Revision ID: 6f61f5539071
Revises: ba30361841af
Create Date: 2026-05-04 12:33:57.236637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f61f5539071'
down_revision: Union[str, Sequence[str], None] = 'ba30361841af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('readingDate', sa.DateTime(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveys')
    # ### end Alembic commands ###
